#! /bin/sh
list=(
	fruit
	mange
	banane
	patato
) 

# list=(fruit,mange,oranfe,apple,vegetable) 

# # printf "%s" "😔 No Result found. Try again 🔴"

# # menu(){
# #     echo -e "\033[36m1: convert MP4 to MP3\e[0m"
# #     echo -e "\033[36m2: record the screen\e[0m"
# #     echo -e "\033[36m3: extract\e[0m"
# #     echo -e "\033[36m4: others\e[0m"
# # }

# printf "%s\n" "${list[@]}" | rofi -fzf --ansi --color=dark --border --prompt='choice a fruit: ' --reverse
# printf "%s" ${list[@]} | fzf --ansi --color=dark --border --prompt='choice a fruit: ' --reverse -d ','
printf "%s" ${list[@]} | fzf --ansi --color=dark --border --prompt='choice a fruit: ' --reverse

# # choice=$(menu | fzf --ansi --color=dark --reverse --border --header='choice one:')

# # echo "${choice%% *}"
