#! /bin/sh

# 1tb='00f51dc0-f732-4ce5-988e-3c6e657fba12'
# 500gb='8b4e900f-cf21-4f38-bd58-878c25f84818'

# mounting(){
#      sudo mount /dev/$name $1
# }

dev=$(lsblk -fm | dmenu -l 20)

UUID=$(echo "$dev"| awk '{print $4}')
# name=$(echo "$dev"| awk '{print $1}'| cut -c 5-)
name=$(echo "$dev"| awk '{print $1}')
name=${name:2:4}
# echo "|$name|"

case $UUID in
   "00f51dc0-f732-4ce5-988e-3c6e657fba12")  
        sudo mount /dev/$name "$HOME/Media/1tb" ;;
   "8b4e900f-cf21-4f38-bd58-878c25f84818")
        sudo mount "/dev/${name}" "$HOME/Media/500gb" ;; 
    *) exit 1 ;;
esac
