#!/bin/bash

#-Helper to mount android phones, works with dmenu
mounting(){
	simple-mtpfs -o default_permissions --device "$dev" $mount_point/ &&
	notify-send "Device mounted on $mount_point"
}

mount_point="$HOME/media/phone"
dev=$(simple-mtpfs -l | fzf )
dev=${dev:0:1}


[ -z "$dev" ] &&  (notify-send "no device to mount" && exit 1)  ||
[ "$(ls $mount_point)" ] && uphone && mounting || mounting 
