#!/bin/sh
# notflix: Search and stream movies (1337x)
# Dependencies: curl, webtorrent (or mpv)

CACHEDIR="$HOME/.cache/notflix"
mkdir -p "$CACHEDIR"

BASEURL="https://1337x.wtf"

if [ -z "$1" ]; then
    QUERY=$(echo "" | sys-menu "Search Torrent:")
else
    QUERY="$1"
fi

[ -z "$QUERY" ] && exit 0
QUERY=$(echo "$QUERY" | sed 's/ /+/g')

curl -s "$BASEURL/search/$QUERY/1/" > "$CACHEDIR/tmp.html"

# Scrape data using grep/sed
grep -o '<a href="/torrent/.*</a>' "$CACHEDIR/tmp.html" | sed 's/<[^>]*>//g' > "$CACHEDIR/titles.bw"
[ ! -s "$CACHEDIR/titles.bw" ] && notify-send "😔 No Result found." && exit 0

grep -o '<td class="coll-2 seeds.*</td>\|<td class="coll-3 leeches.*</td>' "$CACHEDIR/tmp.html" | sed 's/<[^>]*>//g' | sed 'N;s/\n/ /' | awk '{print "[S:"$1 ", L:"$2"]" }' > "$CACHEDIR/seedleech.bw"
grep -o '<td class="coll-4 size.*</td>' "$CACHEDIR/tmp.html" | sed 's/<span class="seeds">.*<\/span>//g' | sed -e 's/<[^>]*>//g' | awk '{print NR " - ["$0"]"}' > "$CACHEDIR/size.bw"
grep -E '/torrent/' "$CACHEDIR/tmp.html" | sed -E 's#.*(/torrent/.*)/">.*/#\1#' | sed 's/td>//g' > "$CACHEDIR/links.bw"

# Format display
LINE=$(paste -d\   "$CACHEDIR/size.bw" "$CACHEDIR/seedleech.bw" "$CACHEDIR/titles.bw" | sys-menu "Select Movie:" | cut -d\- -f1 | tr -d ' ')
[ -z "$LINE" ] && exit 0

URL=$(sed -n "${LINE}p" "$CACHEDIR/links.bw")
MAGNET_PAGE=$(curl -s "${BASEURL}${URL}/")
MAGNET=$(echo "$MAGNET_PAGE" | grep -Po "magnet:\?xt=urn:btih:[a-zA-Z0-9]*" | head -n 1)

if [ -n "$MAGNET" ]; then
    echo "$MAGNET" | sys-clip
    notify-send "🔍 Streaming Magnet seeds 🧲"
    webtorrent "$MAGNET" --mpv
else
    notify-send "Error: Magnet not found."
fi
