monitor.bluez.properties = {
    bluez5.enable-sbc-xq = true
    bluez5.enable-msbc = true
    bluez5.hfp-hf-rate = 8000
}

bluez5.properties = {
    bluez5.reconnect-profiles = [ a2dp_sink hsp_hs hfp_hf ]
    bluez5.hw-volume = [ a2dp_sink hsp_hs hfp_hf ]
}

wireplumber.rules = [
    {
        matches = [
            {
                node.name = "~bluez_output.*"
            }
        ],
        actions = {
            update-props = {
                node.description = "Bluetooth Headphones"
            }
        }
    }
]
