#!/usr/bin/sh

alias ip="ip --color=auto"
alias grep="grep --color=auto"
alias c=clear
alias lr=clear
alias cl=clear
alias clr=clear
alias nf=neofetch
alias sf=screenfetch
alias mc=micro
alias hx=helix
alias pn=pnpm
alias px=pnpx
alias sb="source ~/.bashrc"
alias sz="source ~/.zshrc"
alias eb="$EDITOR ~/.bashrc && sb" 
alias ez="$EDITOR ~/.zshrc && sb" 
alias al="$EDITOR ~/aliasrc && sb"
alias fn="$EDITOR ~/functionrc && sb"
alias fc="$EDITOR ~/functionrc && sb"
alias mdata="sudo mount /dev/sdb2 media/Datas/"
alias phone="simple-mtpfs -o default_permissions --device"
# alias exp="cd ~/media/experiment"
alias del="sudo rm -rf"

# lsd
if [ $(command -v lsd) ]; then
	alias ls=lsd
	alias la="lsd -la"
	alias ll="lsd -lah"
	alias tree="lsd --tree"
else
	alias ls="ls --color=auto"
	alias la="ls -la"
	alias ll="ls -lah"
fi

# bat
[ $(command -v bat) ] && alias cat=bat

# youtube-dlp
alias dlt="yt-dlp -P ~/media/Tuto"
alias dlv="yt-dlp -P ~/media/Videos"
alias dlm="yt-dlp -f 'bestvideo[height<=1080][ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best' -P ~/media/Tuto"
# alias dlm="yt-dlp -f 'bestvideo[height<=1080][ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best' -P ~/media/Clip-Videos"

alias stream="webtorrent --mpv"
alias dlS="webtorrent -o ~/media/Series"

# # aria2p
# alias aria2penv="source $HOME/.virtualenv/aria2p\[tui\]/bin/activate"
# alias dlM="aria2c -s 16 -x 16 -d ~/media/Movies"
# alias dlS="aria2c -s 16 -x 16 -d ~/media/Series"
# alias dlmag="aria2c -d ~/media --enable-dht=true"

# Git
alias ga="git add"
alias gc="git clone"
alias gs="git status"
alias gps="git push"
alias gpl="git pull"
alias gct="git commit -m"

alias del="rm -rf"
alias conf="cd ~/.config"
alias lbin="cd ~/.local/bin"
alias cin="xclip -selection c"
alias cout="xclip -selection clipboard -o | tr -d '\n'"
# alias hst="history|cut -c 8- |sort|uniq|fzf --reverse |tr -d '\n'|wl-copy"
alias hst="history|cut -c 8- |sort|uniq|fzf --reverse |tr -d '\n'|cin"
alias swifi="nmcli dev wifi rescan"
alias connect="nmcli dev wifi connect"
alias disconnect="nmcli con down"

# systemd
alias sysd="sudo systemctl"
alias nsysd="sudo systemctl enable"
alias ssysd="sudo systemctl start"
alias rsysd="sudo systemctl restart"
alias pls=sudo
alias copy="rsync --progress --ignore-existing -rhav"
alias png="ping 8.8.8.8 -c 50"


# System info
alias sysinfo_basic='uname -a'
alias sysinfo_hard='lscpu'
alias sysinfo_kernel='cat /proc/version'
alias sysinfo_memory='free -h'

# Package managers
if [ $(command -v pacman) ]; then
	# Pacman
	alias pkg-i="sudo pacman -S"
	alias pkg-r="sudo pacman -Rns"
	alias pkg-u="sudo pacman -Syyu"
	alias pkg-s="sudo pacman -Ss"
	alias rmpaclock="sudo rm -R /var/lib/pacma/db.lck"
	alias pac-refrech="pack --init && pack --populate && pac -Sy archlinux-keyring && pac -Su" 
	# Paru
	alias p="paru"
	alias ps="paru -S"
	alias pss="paru -Ss"
	alias pq="paru -Qqe"
	alias yay="paru"
	alias ys="paru -S"
	alias yss="paru -Ss"
	alias ysu="paru -Syu"
	alias yq="paru -Qqe"
	alias yr="paru -Rns"
elif [ $(command -v apt) ]; then
	alias pkg-i='sudo apt install' 
	alias pkg-r='sudo apt remove'
	alias pkg-u='sudo apt update'
	alias pkg-s='apt search'
elif [ $(command -v dnf) ]; then
	alias pkg-i='sudo dnf install'
	alias pkg-r='sudo dnf remove' 
	alias pkg-u='sudo dnf update'
	alias pkg-s='dnf search'  
fi