-- Monitor and workspace configuration
-- Replaces configs/Monitors.conf + monitors.conf + workspaces.conf
-- See https://wiki.hypr.land/Configuring/Basics/Monitors/
--
-- NOTE: monitors.conf and workspaces.conf are auto-generated by nwg-displays.
-- Until nwg-displays supports Lua output, we keep the generated values here manually
-- and keep nwg-displays pointed to monitors.conf for regeneration.
-- After running nwg-displays, copy the generated values into this file.

-- Monitors (from nwg-displays generated monitors.conf)
hl.monitor({
    output   = "LVDS-1",
    mode     = "1920x1080@60.03",
    position = "0x0",
    scale    = 1.0,
})

hl.monitor({
    output   = "VGA-2",
    mode     = "1024x768@60.0",
    position = "1920x0",
    scale    = 2.0,
})

-- Workspace rules (from nwg-displays generated workspaces.conf)
-- All workspaces pinned to LVDS-1; workspace 2 is default
hl.workspace_rule({ workspace = 2,  monitor = "LVDS-1", default = true })
hl.workspace_rule({ workspace = 1,  monitor = "LVDS-1" })
hl.workspace_rule({ workspace = 3,  monitor = "LVDS-1" })
hl.workspace_rule({ workspace = 4,  monitor = "LVDS-1" })
hl.workspace_rule({ workspace = 5,  monitor = "LVDS-1" })
hl.workspace_rule({ workspace = 6,  monitor = "LVDS-1" })
hl.workspace_rule({ workspace = 7,  monitor = "LVDS-1" })
hl.workspace_rule({ workspace = 8,  monitor = "LVDS-1" })
hl.workspace_rule({ workspace = 9,  monitor = "LVDS-1" })
hl.workspace_rule({ workspace = 10, monitor = "LVDS-1" })
