-- Monitor and Workspace Configuration
-- Migrated from monitors.conf + workspaces.conf (Hyprland 0.55+ Lua config)
-- https://wiki.hypr.land/Configuring/Basics/Monitors/
--
-- NOTE: monitors.conf and workspaces.conf are auto-generated by nwg-displays.
-- The values below mirror the last generated state. If you use nwg-displays,
-- those files will keep being regenerated as .conf — update this file to match
-- whenever nwg-displays regenerates them.

-- Primary laptop display
hl.monitor({
    output   = "LVDS-1",
    mode     = "1920x1080@60.03",
    position = "0x0",
    scale    = 1.0,
})

-- External VGA monitor (positioned to the right of LVDS-1)
hl.monitor({
    output   = "VGA-2",
    mode     = "1024x768@60.0",
    position = "1920x0",
    scale    = 2.0,
})

-- Catch-all for any other connected monitor
-- hl.monitor({ output = "", mode = "preferred", position = "auto", scale = 1 })

-- Workspace assignments (all workspaces pinned to LVDS-1; workspace 2 is default)
-- These mirror workspaces.conf generated by nwg-displays.
-- hl.workspace rules via window_rules or hl.config workspace pinning as needed.
-- In Hyprland 0.55+ Lua, workspace-to-monitor binding is done via hl.config:
hl.workspace_rule({ workspace = "1", monitor = "LVDS-1" })
hl.workspace_rule({ workspace = "2", monitor = "LVDS-1", default = true })
hl.workspace_rule({ workspace = "3", monitor = "LVDS-1" })
hl.workspace_rule({ workspace = "4", monitor = "LVDS-1" })
hl.workspace_rule({ workspace = "5", monitor = "LVDS-1" })
hl.workspace_rule({ workspace = "6", monitor = "LVDS-1" })
hl.workspace_rule({ workspace = "7", monitor = "LVDS-1" })
hl.workspace_rule({ workspace = "8", monitor = "LVDS-1" })
hl.workspace_rule({ workspace = "9", monitor = "LVDS-1" })
hl.workspace_rule({ workspace = "10", monitor = "LVDS-1" })
